table 'Sales Metrics'
	column Value
		dataType: int64
	column Metric
		dataType: string
		expression: NAMEOF([Total Sales]) & NAMEOF([Avg Sales]) & NAMEOF([Total Quantity])
	measure 'Selected Metric' =
		SWITCH(
			SELECTEDVALUE('Sales Metrics'[Value]),
			0, [Total Sales],
			1, [Avg Sales],
			2, [Total Quantity]
		)
